name: "Release Plugin"

on:
  push:
    branches:
      - development
      - next
      - nitra-main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  deployments: write

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  lint:
    needs: "setup"
    uses: ./.github/workflows/reusable_lint.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  # build-packages:
  #   needs: "setup"
  #   uses: ./.github/workflows/reusable_build.yml
  #   secrets:
  #     THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  release:
    needs: ["setup", "lint"]
    runs-on: "ubuntu-24.04"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

      - name: "Build Packages"
        working-directory: ./packages/capacitor-plugin
        run: |
          npm install
          npm run build

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_WRITE_TOKEN }}
          access: public
          strategy: upgrade
          package: ./packages/capacitor-plugin/package.json
