name: "Release Plugin"

on:
  push:
    branches:
      - development
      - next
      - main
  workflow_dispatch:

permissions:
    contents: write
    issues: write
    deployments: write

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  lint:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  build-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_build.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  release:
    needs: ['setup','lint','build-packages']
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: Release
        working-directory: ./packages/capacitor-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx semantic-release